package gogh_test

import (
	"fmt"
	"io"
	"os"
	"testing"

	"github.com/sirkon/gogh"
)

var importGroups = []gogh.ImportsGroup{
	{
		{
			Path: "C",
		},
	},
	{
		{
			Path: "fmt",
		},
	},
	{
		{
			Alias: "pkg",
			Path:  "github.com/sirkon/gogh",
		},
	},
}

func ExampleGoRendererNoHeadCommentError() {
	var r gogh.Renderer

	r.Line("func main() {")

	_, err := r.Render("", "main", importGroups)
	fmt.Println(err)
	// Output:
	// 11:15: expected ';', found 'EOF' (and 1 more errors)
	//
	// 01: package main
	// 02:
	// 03: import "C"
	// 04:
	// 05: import (
	// 06:     "fmt"
	// 07:
	// 08:     pkg "github.com/sirkon/gogh"
	// 09: )
	// 10:
	// 11: func main() {
	// 12:
}

func ExampleGoRendererHeadSingleLineCommentOK() {
	var r gogh.Renderer

	r.Line(`func main() {`)
	r.Line(`}`)

	src, err := r.RenderAutogen("application", "main", importGroups)
	if err != nil {
		fmt.Println(err)
	} else {
		_, _ = io.Copy(os.Stdout, src)
	}
	// Output:
	// // Code generate with application. DO NOT EDIT.
	//
	// package main
	//
	// import "C"
	//
	// import (
	//	"fmt"
	//
	//	pkg "github.com/sirkon/gogh"
	// )
	//
	// func main() {
	// }
}

func ExampleGoRendererHeadMultiLineCommentOK() {
	var r gogh.Renderer

	r.Line(`func main() {`)
	r.Line(`}`)

	src, err := r.Render("autogenerated code\napplication", "main", importGroups)
	if err != nil {
		fmt.Println(err)
	} else {
		_, _ = io.Copy(os.Stdout, src)
	}
	// Output:
	// /*
	// autogenerated code
	// application
	// */
	//
	// package main
	//
	// import "C"
	//
	// import (
	//	"fmt"
	//
	//	pkg "github.com/sirkon/gogh"
	// )
	//
	// func main() {
	// }
}

func TestRendererRawString(t *testing.T) {
	var r gogh.Renderer
	line := `a := &Struct{`
	r.Line(line)

	lineNL := line + "\n"
	if r.RawString() != lineNL {
		t.Errorf("`%s` expected, got `%s`", lineNL, r.RawString())
	}
}
