package gogh

import (
	"bytes"
	"os"
	"runtime/debug"

	"github.com/sirkon/errors"
	"github.com/sirkon/message"
)

// GoRendererOption an option to be applied before the code rendering. Returns false if rendering should be stopped.
// hiddenType is used to prevent user-defined options which barely makes any sense.
type GoRendererOption[T Importer] func(_ hiddenType, r *GoRenderer[T]) bool

// Shy prevents overwrite of existing file
func Shy[T Importer](_ hiddenType, r *GoRenderer[T]) bool {
	_, err := os.Stat(r.path())
	if err == nil {
		// file exists
		message.Warning("will not overwrite existing file", r.localPath())
		return false
	}

	if errors.Is(err, os.ErrNotExist) {
		return true
	}

	panic(errors.Wrapf(err, "get file info"))
}

// Autogen puts header `Code generated by <app name> version vX.Y.Z. DO NOT EDIT.`
func Autogen[T Importer](appname string) GoRendererOption[T] {
	return func(_ hiddenType, r *GoRenderer[T]) bool {
		r.comment = &bytes.Buffer{}
		r.comment.WriteString("Code generated by ")
		r.comment.WriteString(appname)
		r.comment.WriteString(" version ")
		info, ok := debug.ReadBuildInfo()
		if !ok {
			r.comment.WriteString("(devel)")
		} else {
			r.comment.WriteString(info.Main.Version)
		}
		r.comment.WriteString(". DO NOT EDIT.")

		return true
	}
}
