// Code generated by testexample version (devel). DO NOT EDIT.

package testexample

import "github.com/sirkon/errors"

func newExample() error {
	return errors.New("something failed").Str("something", "value")
}
func newfExample() error {
	return errors.Newf("%s %d", "error", 1)
}
func wrapExample() error {
	return errors.Wrap(newExample(), "call new")
}
func wrapfExample() error {
	return errors.Wrapf(newExample(), "call %s", "new")
}
